# Generated by Django 3.0.3 on 2020-04-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'AboutUs', 'verbose_name_plural': 'AboutUs'},
        ),
        migrations.AlterModelOptions(
            name='chef',
            options={'verbose_name': 'Chef', 'verbose_name_plural': 'Chefs'},
        ),
        migrations.AlterModelOptions(
            name='whychooseus',
            options={'verbose_name': 'WhyChooseUs', 'verbose_name_plural': 'WhyChooseUs'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
    ]
