# Generated by Django 3.0.3 on 2020-04-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
    ]
